"""init tables

Revision ID: 75b955c8933f
Revises: 
Create Date: 2026-10-07 01:06:06.358719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75b955c8933f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('edit_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='编辑时间：业务代码手动更新',
               existing_comment='编辑时间：业务代码手动更新（创建者修改时更新）',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间：数据库自动更新',
               existing_comment='更新时间：数据库自动更新（任何修改触发）',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_app_name'))
        batch_op.drop_index(batch_op.f('idx_app_user_id'))
        batch_op.drop_table_comment(
        existing_comment='应用（AI生成的网页应用）'
    )

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=32),
               comment='消息类型：user/ai',
               existing_comment='消息类型：system/user/assistant',
               existing_nullable=True)
        batch_op.alter_column('app_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='应用id')
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='创建用户id')
        batch_op.drop_index(batch_op.f('idx_app_id'))
        batch_op.drop_index(batch_op.f('idx_app_id_create_time'))
        batch_op.drop_index(batch_op.f('idx_create_time'))
        batch_op.create_foreign_key(None, 'app', ['app_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_table_comment(
        existing_comment='对话历史'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('edit_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='编辑时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_user_name'))
        batch_op.drop_index(batch_op.f('uk_user_account'))
        batch_op.create_index(batch_op.f('ix_user_user_account'), ['user_account'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_user_name'), ['user_name'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_user_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_user_account'))
        batch_op.create_index(batch_op.f('uk_user_account'), ['user_account'], unique=True)
        batch_op.create_index(batch_op.f('idx_user_name'), ['user_name'], unique=False)
        batch_op.alter_column('edit_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='编辑时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_table_comment(
        '对话历史',
        existing_comment=None
    )
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_create_time'), ['create_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_id_create_time'), ['app_id', 'create_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_id'), ['app_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='创建用户id')
        batch_op.alter_column('app_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='应用id')
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=32),
               comment='消息类型：system/user/assistant',
               existing_comment='消息类型：user/ai',
               existing_nullable=True)

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_table_comment(
        '应用（AI生成的网页应用）',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_app_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_name'), ['app_name'], unique=False)
        batch_op.alter_column('update_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间：数据库自动更新（任何修改触发）',
               existing_comment='更新时间：数据库自动更新',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('edit_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='编辑时间：业务代码手动更新（创建者修改时更新）',
               existing_comment='编辑时间：业务代码手动更新',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
