"""init tables

Revision ID: fca4825303d2
Revises: 
Create Date: 2026-10-07 05:24:38.206061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca4825303d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='id'),
    sa.Column('message', sa.Text(), nullable=False, comment='消息'),
    sa.Column('message_type', sa.String(length=32), nullable=True, comment='消息类型：user/ai'),
    sa.Column('app_id', sa.BigInteger(), nullable=True, comment='应用id'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='创建用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='token数量'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index('idx_app_id_create_time', ['app_id', 'create_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_create_time'), ['create_time'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='id'),
    sa.Column('user_account', sa.String(length=256), nullable=False, comment='账号'),
    sa.Column('user_password', sa.String(length=512), nullable=False, comment='密码'),
    sa.Column('user_name', sa.String(length=256), nullable=True, comment='用户昵称'),
    sa.Column('user_avatar', sa.String(length=1024), nullable=True, comment='用户头像'),
    sa.Column('user_profile', sa.String(length=512), nullable=True, comment='用户简介'),
    sa.Column('user_role', sa.String(length=256), nullable=False, comment='用户角色：user/admin'),
    sa.Column('edit_time', sa.DateTime(), nullable=False, comment='编辑时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_user_account'), ['user_account'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_user_name'), ['user_name'], unique=False)

    op.create_table('app',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='id'),
    sa.Column('app_name', sa.String(length=256), nullable=False, comment='应用名称'),
    sa.Column('app_coverage', sa.String(length=1024), nullable=True, comment='应用封面图标URL'),
    sa.Column('init_prompt', sa.Text(), nullable=True, comment='应用初始化的用户Prompt'),
    sa.Column('code_gen_type', sa.String(length=64), nullable=True, comment='代码生成类型：枚举值（如html/css/js/multi_file等）'),
    sa.Column('deploy_key', sa.String(length=64), nullable=True, comment='应用部署唯一标识ID'),
    sa.Column('deploy_time', sa.DateTime(), nullable=True, comment='部署时间：未部署时为NULL'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='首页展示优先级'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='创建用户ID（关联user表id）'),
    sa.Column('edit_time', sa.DateTime(), nullable=False, comment='编辑时间：业务代码手动更新'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间：数据库自动更新'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=False, comment='是否删除：0-正常，1-已删除'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deploy_key')
    )
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_app_name'))

    op.drop_table('app')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_user_account'))

    op.drop_table('user')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_create_time'))
        batch_op.drop_index(batch_op.f('ix_chat_history_app_id'))
        batch_op.drop_index('idx_app_id_create_time')

    op.drop_table('chat_history')
    # ### end Alembic commands ###
